import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/banner/Banner'
import styles from '../styles/Home.module.css'
import Navbar from '../components/nav/navbar'
import SectionCards from '../components/card/SectionCards'

export default function Home() {

  const marvelVideos = [
    {
      imgUrl: '/static/venom.jpg',
      
    },
    {
      imgUrl: '/static/venom.jpg',

    },
    {
      imgUrl: '/static/venom.jpg',

    }
  ]
  return (
    <div className={styles.container}>
      <Head>
        <title>netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner
        title="The batman"
        subtitle="the hero"
        imgUrl="https://ia.tmgrup.com.tr/818842/0/0/0/0/947/528?u=https://i.tmgrup.com.tr/es/2021/10/18/robert-pattinsonli-the-batmandan-fragman-geldi-1634550792568.jpeg"
      />
      <div className={styles.sectionWrapper}>
        <SectionCards title="Marvel" videos={marvelVideos} size='large'/>
        <SectionCards title="Marvel" videos={marvelVideos} size='medium'/>
      </div>
      <Navbar username="Laurent" />
    </div>
  );
}
